# @package _global_

name: "dbg_base"

dataset: "conflab-dataset-debug"
coco_json_path: "store/dbg_conflab_coco.json"

# whether to use small keypoint
kp_rank: 0 # 1,2,3

prefix_path: "dbg_"

coco_json_path_train: "store/${prefix_path}conflab_coco_train${coco_json_prefix}${kp_rank}.json"
coco_json_path_test: "store/${prefix_path}conflab_coco_test${coco_json_prefix}${kp_rank}.json"

total_im_per_vid: 5
